-- 20250920104000_run_number_scoped_unique.sql
-- Make payroll_runs.run_number exist and enforce uniqueness per company.

BEGIN;

-- 1) Ensure the column exists
ALTER TABLE public.payroll_runs
  ADD COLUMN IF NOT EXISTS run_number text;

-- 2) Drop a previous single-column unique constraint if present
--    Default autogenerated name is usually payroll_runs_run_number_key
ALTER TABLE public.payroll_runs
  DROP CONSTRAINT IF EXISTS payroll_runs_run_number_key;

-- 3) Create a composite unique index scoped to company + run_number
CREATE UNIQUE INDEX IF NOT EXISTS uq_payroll_runs_company_run_number
  ON public.payroll_runs(company_id, run_number);

COMMIT;
