name: ci

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    name: Typecheck, Lint, Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Get pnpm store path
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Typecheck
        run: |
          if [ -f "tsconfig.json" ]; then
            pnpm exec tsc --noEmit
          else
            echo "No tsconfig.json found, skipping"
          fi

      - name: Lint
        run: |
          if [ -f "package.json" ] && jq -e '.scripts.lint' package.json > /dev/null; then
            pnpm run lint
          else
            echo "No lint script, skipping"
          fi

      - name: Build
        env:
          NEXT_PUBLIC_APP_ENV: "ci"
        run: |
          if [ -f "package.json" ] && jq -e '.scripts.build' package.json > /dev/null; then
            pnpm run build
          else
            echo "No build script, skipping"
          fi

      - name: Unit tests (if present)
        run: |
          if [ -f "package.json" ] && jq -e '.scripts.test' package.json > /dev/null; then
            pnpm run test --if-present -- --ci --reporter=default
          else
            echo "No tests yet, skipping"
          fi
