name: WageFlow CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  ci:
    name: Lint, Type-check, Build, Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Configure npm for clean CI
        run: |
          npm config set fund false
          npm config set audit false

      - name: Install dependencies
        run: npm ci

      - name: Lint
        if: ${{ hashFiles('**/.eslintrc*', '**/eslint.config.*') != '' }}
        run: npm run lint --if-present

      - name: Type check
        run: |
          if npm run -s | grep -q "^type-check"; then
            npm run type-check
          else
            echo "No type-check script, running tsc --noEmit"
            npx tsc --noEmit
          fi

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test --if-present -- --ci --reporters=default
